# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: de20fec93cfc0391d977cd6f8f0f2295e92782feaf723333ea2f03f8bc2e65ec82092142fde4618d57846eeb870b7d37d27f14122d4c3b913babb51f0d0ee457

test:
  secret_key_base: 917d487d2e6baf1b30ed2fdd2dd3ce25273a95f6b1a5ad1a5359874bc863116d7b337714528e8829e80ceceb93592d53ee2609a116584183f9fe76364f3bf212

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
